import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'caseStudy',
  title: 'Case Study',
  type: 'document',
  fields: [
    defineField({ name: 'client', title: 'Client Name', type: 'string', validation: r => r.required() }),
    defineField({ name: 'slug', title: 'Slug', type: 'slug', options: { source: 'client' }, validation: r => r.required() }),
    defineField({ name: 'industry', title: 'Industry', type: 'string' }),
    defineField({ name: 'summary', title: 'Summary', type: 'text', rows: 3 }),
    defineField({ name: 'challenge', title: 'The Challenge', type: 'text', rows: 5 }),
    defineField({ name: 'solution', title: 'Our Approach', type: 'text', rows: 5 }),
    defineField({ name: 'results', title: 'The Results', type: 'text', rows: 5 }),
    defineField({ name: 'metric1_num', title: 'Metric 1 Number', type: 'string' }),
    defineField({ name: 'metric1_label', title: 'Metric 1 Label', type: 'string' }),
    defineField({ name: 'metric2_num', title: 'Metric 2 Number', type: 'string' }),
    defineField({ name: 'metric2_label', title: 'Metric 2 Label', type: 'string' }),
    defineField({ name: 'metric3_num', title: 'Metric 3 Number', type: 'string' }),
    defineField({ name: 'metric3_label', title: 'Metric 3 Label', type: 'string' }),
    defineField({
      name: 'accent', title: 'Accent Color', type: 'string',
      options: { list: ['purple', 'cyan', 'gold'] },
    }),
    defineField({ name: 'coverImage', title: 'Cover Image', type: 'image', options: { hotspot: true } }),
    defineField({ name: 'published', title: 'Published', type: 'boolean', initialValue: true }),
    defineField({
      name: 'featured',
      title: 'Featured in Nav',
      type: 'boolean',
      initialValue: false,
      description: 'Show this case study in the Industries nav dropdown. Only one should be featured at a time.',
    }),
    defineField({
      name: 'navMetric',
      title: 'Nav Metric',
      type: 'string',
      description: 'Short result quote shown in the nav card, e.g. "62% faster deal cycle". Keep under 40 characters.',
    }),
    defineField({
      name: 'seoTitle',
      title: 'SEO Title',
      type: 'string',
      description: 'Overrides the page title in search results. 50–60 characters recommended.',
    }),
    defineField({
      name: 'seoDescription',
      title: 'SEO Description',
      type: 'text',
      rows: 3,
      description: 'Overrides the meta description in search results. 140–160 characters recommended.',
    }),
  ],
  preview: { select: { title: 'client', subtitle: 'industry', media: 'coverImage' } },
})
